"""agregar_stock_requerido

Revision ID: 83fd38f7fa3c
Revises: 8c50e4ec4824
Create Date: 2026-04-28 17:22:15.612440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fd38f7fa3c'
down_revision = '8c50e4ec4824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_requerido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock_requerido')

    # ### end Alembic commands ###
