"""Agregar campos de notificaciones

Revision ID: 9adf3a583675
Revises: c344549ac839
Create Date: 2026-03-16 11:26:18.299810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adf3a583675'
down_revision = 'c344549ac839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_notificacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('ultima_notificacion')

    # ### end Alembic commands ###
