"""agregar_stock_requerido

Revision ID: e20f3e16a407
Revises: 83fd38f7fa3c
Create Date: 2026-04-28 17:24:15.862521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20f3e16a407'
down_revision = '83fd38f7fa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
