"""Agregar campos dde precios, mesa de cambio en bs de usd

Revision ID: f6f3348c7ed7
Revises: 9adf3a583675
Create Date: 2026-03-16 12:04:32.959001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f3348c7ed7'
down_revision = '9adf3a583675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_mayor_bs', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_mayor_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_detal_bs', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_detal_usd', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio_detal_usd')
        batch_op.drop_column('precio_detal_bs')
        batch_op.drop_column('precio_mayor_usd')
        batch_op.drop_column('precio_mayor_bs')

    # ### end Alembic commands ###
