"""Add marca to Producto and ModeloTelefono

Revision ID: b1a153a43c5e
Revises: 40236a22c027
Create Date: 2026-03-27 10:31:08.105978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a153a43c5e'
down_revision = '40236a22c027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelos_telefono', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('marca')

    with op.batch_alter_table('modelos_telefono', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
