"""Add precio tecnico for screens

Revision ID: 40236a22c027
Revises: f6f3348c7ed7
Create Date: 2026-03-24 10:54:41.842639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40236a22c027'
down_revision = 'f6f3348c7ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_tecnico_bs', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_tecnico_usd', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio_tecnico_usd')
        batch_op.drop_column('precio_tecnico_bs')

    # ### end Alembic commands ###
